version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "youtube-notification-serverless-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-me1jiodyparl"
s3_prefix = "youtube-notification-serverless-bot"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
