# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  youtube_notification_serverless_bot

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  authInitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/auth.authInitHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Init Google API OAuth2 auth
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          GOOGLE_CLIENT_REDIRECT_URL: !Ref GoogleClientRedirectUrl
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth
            Method: GET

  authCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/auth.authCallbackHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Callback for Google API OAuth2 auth
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GoogleTokenDynamoDbTable
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          GOOGLE_CLIENT_REDIRECT_URL: !Ref GoogleClientRedirectUrl
          GOOLGE_TOKEN_DYNAMODB_TABLE: !Ref GoogleTokenDynamoDbTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth/callback
            Method: GET

  notificationRefreshFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/notification-refresh.notificationRefreshHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Refresh subscription to all channels
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GoogleTokenDynamoDbTable
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          GOOGLE_CLIENT_REDIRECT_URL: !Ref GoogleClientRedirectUrl
          GOOLGE_TOKEN_DYNAMODB_TABLE: !Ref GoogleTokenDynamoDbTable
          NOTIFICATION_SUBSCRIPTION_HOST: !Ref NotificationSubscriptionHost
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 0/6 * * ? *)

  notificationSubscriberFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/notification-subscriber.notificationSubscriberHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Catch subscription from YouTube channel
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDbTable
      Environment:
        Variables:
          VIDEOS_DYNAMODB_TABLE: !Ref DynamoDbTable
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_CHANNEL_ID: !Ref TelegramChannelId
          TELEGRAM_ACKNOWLEDGE_SEND: !Ref TelegramAcknowledgeSend
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /subscriber
            Method: ANY

  GoogleTokenDynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: youtube-notification-serverless-bot-token
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  DynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: youtube-notification-serverless-bot
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Parameters:
  GoogleClientId:
    Type: String
  GoogleClientSecret:
    Type: String
  GoogleClientRedirectUrl:
    Type: String
  NotificationSubscriptionHost:
    Type: String
  TelegramBotToken:
    Type: String
  TelegramChannelId:
    Type: String
  TelegramAcknowledgeSend:
    Type: String

Outputs:
  GoogleAuthInit:
    Description: "Init Google API OAuth2 auth"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/auth"
  GoogleAuthCallback:
    Description: "Callback for Google API OAuth2 auth"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/auth/callback"
  NotificationSubscriber:
    Description: Catch subscription from YouTube channel
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/subscriber"
